### ISSUE TITLE
pca plot not loaded---urgent please

### ISSUE THREAD

**Issue by garimaloh** [mani2012/BatchQC#17]
<img width="925" alt="Capture" src="https://user-images.githubusercontent.com/48873678/87845504-056e8480-c896-11ea-9110-8e04b817d196.PNG">

Unable to generate plot. The table is loaded. Other data is present in Summary, Table and Explained variation tab.

**Comment by mani2012** [comment]
Hi,

Thank you for contacting. This is a known issue with ggvis. (https://github.com/rstudio/ggvis/issues/483).
I am hoping that the maintainers of ggvis will fix this soon.
Fortunately, there is an easy fix for now so that you can get back this plot working in no time. All you do is the following:
You will need to downgrade the dplyr package to version 0.8.3. Locate your R repository location:
For example in Windows: <Documents>\R\win-library\4.0
Delete the folder dplyr or Move the folder dplyr to some other location for now.

Install the package devtools, if you don’t have it already and run the following.
require(devtools)
install_version("dplyr", version = "0.8.3")

Please let me know whether your plot works after downgrading the dplyr to version 0.8.3.

Thanks,
Mani

**Comment by garimaloh** [comment]
Thank you so much. Yes, I have to downgrade the following and it worked.
ggvis_0.4.5

dplyr_0.8.3
shiny_1.4.0.2

htmltools_0.4.0

https://github.com/rstudio/ggvis/issues/483#issuecomment-652257242
